package com.google.android.finsky.config;

import com.google.android.play.utils.config.GservicesValue;

public final class G
{
  public static final String[] GSERVICES_KEY_PREFIXES = { "android_id", "finsky.", "vending_", "logging_id2", "market_client_id" };
  public static GservicesValue<Long> adIdMaxCacheTimeMs;
  public static GservicesValue<Integer> adIdMinGmsCoreVersion;
  public static final GservicesValue<String> additionalRemovedPermissionsM;
  public static final GservicesValue<String> additionalTargets;
  public static final GservicesValue<Boolean> alwaysUseOptionalPermissionBucketsM;
  public static GservicesValue<Boolean> analyticsEnabled;
  public static GservicesValue<Boolean> antiMalwareActivityEnabled;
  public static GservicesValue<Boolean> antiMalwareConsentRequired;
  public static final GservicesValue<Integer> appInBgCheckPollIntervalMs = GservicesValue.value("finsky.app_in_bg_check_poll_interval_ms", Integer.valueOf(10000));
  public static final GservicesValue<Integer> appInBgDurationForUpdatingExperimentsMs;
  public static final GservicesValue<Integer> appRestoreAppIconMaxAttempts;
  public static final GservicesValue<Integer> appRestoreDownloadMaxAttempts;
  public static final GservicesValue<Long> appRestoreFailsafeMs;
  public static final GservicesValue<Integer> appRestoreFetchListMaxAttempts;
  public static final GservicesValue<Long> appRestoreHoldoffMs;
  public static final GservicesValue<String> appRestoreHttpStatusBlacklist;
  public static final GservicesValue<Long> appRestoreRetryDownloadHoldoffHighPriorityMs;
  public static final GservicesValue<Long> appRestoreRetryDownloadHoldoffMs;
  public static final GservicesValue<Long> appRestoreRetryFetchListHoldoffMs;
  public static GservicesValue<String> appsWidgetUrl;
  public static final GservicesValue<Long> authChallengeSessionDurationMs;
  public static final GservicesValue<Long> autoUpdateBroadcastDebouncerDelayMs;
  public static final GservicesValue<Long> autoUpdateBroadcastStabilizerDelayMs;
  public static final GservicesValue<Long> autoUpdateDeliveryHoldoffMs;
  public static final GservicesValue<Integer> autoUpdateDialogFirstBackoffDays;
  public static final GservicesValue<Integer> autoUpdateDialogSecondBackoffDays;
  public static final GservicesValue<Integer> autoUpdateDialogSubsequentBackoffDays;
  public static final GservicesValue<Boolean> autoUpdateExcludeForegroundServices;
  public static final GservicesValue<Boolean> autoUpdateExcludeRunningPackagesPre;
  public static final GservicesValue<Long> autoUpdateGearheadCheckIntervalMs;
  public static final GservicesValue<Long> autoUpdateJobSchedulerGearheadTimeoutMs;
  public static final GservicesValue<Long> autoUpdateJobSchedulerMaxTimeoutMs;
  public static final GservicesValue<Long> autoUpdateJobSchedulerMinTimeoutMs;
  public static final GservicesValue<Long> autoUpdateSkipPowerCheckIntervalMs;
  public static final GservicesValue<Long> autoUpdateThrottleIntervalMs;
  public static final GservicesValue<Long> autoUpdateWifiCheckIntervalMs;
  public static final GservicesValue<Long> backStackExpirationDurationMs;
  public static GservicesValue<String> booksWidgetUrl;
  public static final GservicesValue<Integer> clientMutationCacheCirclesModelCacheSize;
  public static final GservicesValue<Long> clusterPrivacySettingNoticeWindowTimeMs;
  public static GservicesValue<String> consumptionAppDataFilter;
  public static final GservicesValue<Long> consumptionAppImageTimeoutMs;
  public static final GservicesValue<Long> consumptionAppTimeoutMs;
  public static GservicesValue<String> contentFilterInfoUrl;
  public static final GservicesValue<Long> continueUrlExpirationMs;
  public static final GservicesValue<Integer> corpusAwarenessThresholdBooks;
  public static final GservicesValue<Integer> corpusAwarenessThresholdMagazines;
  public static final GservicesValue<Integer> corpusAwarenessThresholdMovies;
  public static final GservicesValue<Integer> corpusAwarenessThresholdMusic;
  public static GservicesValue<Long> crashFileExpiredTimeoutMs;
  public static final GservicesValue<Long> dailyHygieneBootDelayMs;
  public static final GservicesValue<Boolean> dailyHygieneHoldoffDuringSelfUpdate;
  public static final GservicesValue<Long> dailyHygieneHoldoffIntervalMs;
  public static final GservicesValue<Long> dailyHygieneImmediateDelayMs;
  public static final GservicesValue<Integer> dailyHygieneImmediateRunVersionCodeHigh;
  public static final GservicesValue<Integer> dailyHygieneImmediateRunVersionCodeLow;
  public static final GservicesValue<Float> dailyHygieneInitialJitterFactor;
  public static final GservicesValue<Float> dailyHygieneJitterFactor;
  public static final GservicesValue<Boolean> dailyHygienePreloadExperiments;
  public static final GservicesValue<Long> dailyHygieneProvisionHoldoffMaxMs;
  public static final GservicesValue<Long> dailyHygieneRegularIntervalMs;
  public static final GservicesValue<Long> dailyHygieneRetryIntervalMs;
  public static GservicesValue<Integer> dcb3PassphraseKeyVersion;
  public static GservicesValue<Boolean> dcb3PrepareSendDeviceRebooted;
  public static GservicesValue<Integer> dcb3VerifyAssociationRetries;
  public static GservicesValue<Boolean> debugLimitedUserState;
  public static GservicesValue<Boolean> debugOptionsEnabled;
  public static final GservicesValue<Integer> defaultPurchaseAuthentication;
  public static final GservicesValue<Long> deliveryDataExpirationMs;
  public static GservicesValue<Boolean> deviceManagementHelperEnabled;
  public static GservicesValue<Boolean> dfeLogsAdMobEnabled;
  public static GservicesValue<Boolean> dfeManagedContextDetectionEnabled;
  public static final GservicesValue<Boolean> directToBackendIntent;
  public static final GservicesValue<Boolean> disableSidewinderSelfupdate;
  public static final GservicesValue<Long> downloadBytesOverMobileMaximum;
  public static final GservicesValue<Long> downloadBytesOverMobileRecommended;
  public static final GservicesValue<Long> downloadExternalFileSizeMinBytes;
  public static final GservicesValue<Integer> downloadExternalFreeSpaceFactor;
  public static final GservicesValue<Long> downloadExternalFreeSpaceThresholdBytes;
  public static final GservicesValue<Integer> downloadFreeSpaceApkSizeFactor;
  public static final GservicesValue<Long> downloadFreeSpaceThresholdBytes;
  public static final GservicesValue<Integer> downloadPatchFreeSpaceFactor;
  public static final GservicesValue<Boolean> downloadSendBaseVersionCode;
  public static final GservicesValue<String> editPaymentMethodUrl;
  public static final GservicesValue<String> eduDevicePolicyApp;
  public static GservicesValue<String> emailToReportBadAd;
  public static final GservicesValue<Boolean> enableAutoUpdatePowerAndWifiBroadcastListener;
  public static GservicesValue<Boolean> enableCorpusWidgets;
  public static final GservicesValue<Boolean> enableDcbReducedBillingAddress;
  public static final GservicesValue<Boolean> enableDetailsApi;
  public static GservicesValue<Boolean> enableGaiaRecovery;
  public static final GservicesValue<Boolean> enableOkHttp;
  public static final GservicesValue<Boolean> enablePeopleSuggestWidget;
  public static GservicesValue<Boolean> enablePlayLogs;
  public static GservicesValue<Boolean> enableRemoveAppsFromLibrary;
  public static GservicesValue<Boolean> enableReviewComments;
  public static GservicesValue<Boolean> enableSensitiveLogging;
  public static final GservicesValue<Boolean> enableSessionStatsLog;
  public static final GservicesValue<Boolean> enableThirdPartyDetailsApi;
  public static final GservicesValue<Boolean> enableThirdPartyDirectPurchases;
  public static final GservicesValue<Boolean> enableThirdPartyInlineAppInstalls;
  public static GservicesValue<Integer> experimentDefaultMainCacheSizeMb;
  public static final GservicesValue<String> externalReferrerInstallDeepLink;
  public static final GservicesValue<String> externalReferrerInstallOrganic;
  public static final GservicesValue<Long> externalReferrerLifespanMs;
  public static final GservicesValue<String> familyManagementPackage;
  public static final GservicesValue<String> feedbackPackage;
  public static final GservicesValue<Integer> feedbackPackageMinimumVersion;
  public static final GservicesValue<Integer> firstNewsstandAppVersion;
  public static GservicesValue<Long> flushLogsNoUserActivityTimeoutMs;
  public static GservicesValue<Long> flushLogsOnAppExitSelfUpdateTimeoutMs;
  public static GservicesValue<Long> flushLogsOnAppExitTimeoutMs;
  public static GservicesValue<Long> flushLogsScheduleExpiredTimeoutMs;
  public static GservicesValue<Long> flushLogsWaitTimeoutMs;
  public static GservicesValue<Boolean> forcePostPurchaseCrossSell;
  public static final GservicesValue<Long> gaiaAuthValidityMs;
  public static final GservicesValue<String> gaiaOptOutLearnMoreLink;
  public static GservicesValue<String> gamesBrowseUrl;
  public static final GservicesValue<Boolean> gearheadExternalHostingLockout;
  public static final GservicesValue<String> gelPackageName;
  public static GservicesValue<Integer> giftMessageMaxCharacterCount;
  public static final GservicesValue<Boolean> gmsCoreAutoUpdateEnabled;
  public static final GservicesValue<Boolean> gmsCoreAutoUpdateProjectionHoldoff;
  public static GservicesValue<Boolean> gtvNavigationalSuggestEnabled;
  public static final GservicesValue<Long> hasFopCacheTimeoutMs;
  public static final GservicesValue<String> helpCenterBackgroundDataUrl;
  public static final GservicesValue<String> helpCenterManagingSubscriptionsUrl;
  public static GservicesValue<String> helpUrlForConnectionIssues;
  public static GservicesValue<String> helpUrlForCrashingIssues;
  public static GservicesValue<String> helpUrlForDownloadIssues;
  public static GservicesValue<String> helpUrlForExternalStorageMissing;
  public static GservicesValue<String> helpUrlForGeneralIssues;
  public static GservicesValue<String> helpUrlForPurchaseIssues;
  public static GservicesValue<String> helpUrlForStorageIssues;
  public static final GservicesValue<String> homeBrowseUrlsForUserContextHeader;
  public static final GservicesValue<Boolean> iabV3FirstPartyApiEnabled;
  public static final GservicesValue<Boolean> iabV3FirstPartyApiUnrestrictedAccess;
  public static GservicesValue<Integer> iabV3MaxPurchasesInResponse;
  public static GservicesValue<Long> iabV3NetworkTimeoutMs;
  public static GservicesValue<Integer> iabV3SkuDetailsMaxSize;
  public static final GservicesValue<Boolean> iabV3SubscriptionsEnabled;
  public static GservicesValue<Integer> imageCacheSizeMb;
  public static final GservicesValue<Integer> initializeBillingDelayMs;
  public static final GservicesValue<Boolean> launchUrlsEnabled;
  public static final GservicesValue<String> legacyFeedbackPackage;
  public static GservicesValue<String> legalNoticeMenuTitleOverride;
  public static GservicesValue<String> legalNoticeMenuUrl;
  public static final GservicesValue<Integer> libraryReplicatorRescheduleDelayMs;
  public static final GservicesValue<Long> lightPurchaseAutoDismissMs;
  public static final GservicesValue<Long> locationMaxAgeMs;
  public static final GservicesValue<Boolean> logInlineAppInstallReferrerEnabled;
  public static GservicesValue<Integer> logsDispatchIntervalSeconds;
  public static GservicesValue<Integer> mainCacheSizeMb = GservicesValue.value("finsky.main_cache_size_mb", Integer.valueOf(1));
  public static final GservicesValue<Integer> maxAutoUpdateDialogShownCount;
  public static GservicesValue<Integer> maxCrashCount;
  public static GservicesValue<Integer> maxLogQueueSizeBeforeFlush;
  public static final GservicesValue<Integer> maxPrivacySettingNoticeSeenCount;
  public static GservicesValue<Integer> minCrashCountToPurgeCache;
  public static GservicesValue<Integer> minCrashCountToPurgeIntermediateData;
  public static GservicesValue<Integer> minCrashCountToPurgeUserPreferences;
  public static final GservicesValue<Integer> minGmsCoreVersionForFamily;
  public static GservicesValue<Integer> minLocationUpdateRangeMeters;
  public static final GservicesValue<Integer> minimumMusicVersionCode;
  public static final GservicesValue<Integer> minimumNumberOfRecs;
  public static final GservicesValue<Integer> minimumVideosVersionCodeHoneycombPlus;
  public static final GservicesValue<Integer> minimumVideosVersionCodePreHoneycomb;
  public static GservicesValue<String> moviesWidgetUrl;
  public static final GservicesValue<String> musicAllAccessSignUpIntentUrl;
  public static final GservicesValue<String> musicAllAccessSubscriptionBackendDocid;
  public static final GservicesValue<String> musicAppSubscriptionBackendDocidBlacklist;
  public static final GservicesValue<Boolean> musicAppSubscriptionResignupEnabled;
  public static final GservicesValue<String> musicArtistRadioIntentUrl;
  public static final GservicesValue<String> musicDmcaReportLink;
  public static GservicesValue<String> musicWidgetUrl;
  public static final GservicesValue<String> myLibraryWidgeMidtermScores;
  public static final GservicesValue<Boolean> myLibraryWidgetAlwaysIncludeMostRecentBackend;
  public static final GservicesValue<String> myLibraryWidgetBackgroundImageLocation;
  public static final GservicesValue<String> myLibraryWidgetHasContentScoreMap;
  public static final GservicesValue<Float> myLibraryWidgetImportantContributionFraction;
  public static final GservicesValue<Long> myLibraryWidgetInteractionClusterMs;
  public static final GservicesValue<Long> myLibraryWidgetMidtermDurationMs;
  public static final GservicesValue<Float> myLibraryWidgetShorttermDecay;
  public static final GservicesValue<Long> myLibraryWidgetShorttermDurationMs;
  public static final GservicesValue<String> myLibraryWidgetShorttermScores;
  public static final GservicesValue<Integer> newsstandFreeSampleMagazinesAppVersion;
  public static final GservicesValue<Integer> newsstandFreeSubscriptionCompletionAppVersion;
  public static GservicesValue<String> newsstandPostBaseUrl;
  public static final GservicesValue<Integer> nlpCleanupConfigurationId;
  public static final GservicesValue<String> nlpCleanupCookieName;
  public static final GservicesValue<String> nlpCleanupCookieNameTestKeys;
  public static final GservicesValue<String> nlpCleanupCookieValue;
  public static final GservicesValue<String> nlpCleanupCookieValueTestKeys;
  public static final GservicesValue<Boolean> nlpCleanupDowngradeFlag;
  public static final GservicesValue<String> nlpCleanupExpectedSignature;
  public static final GservicesValue<String> nlpCleanupExpectedSignatureTestKeys;
  public static final GservicesValue<Integer> nlpCleanupFlagsMask;
  public static final GservicesValue<Integer> nlpCleanupFlagsSet;
  public static final GservicesValue<Boolean> nlpCleanupLogCommonStatuses;
  public static final GservicesValue<Integer> nlpCleanupNlpVersionMax;
  public static final GservicesValue<Integer> nlpCleanupNlpVersionMin;
  public static final GservicesValue<Integer> nlpCleanupSdkVersionMax;
  public static final GservicesValue<Integer> nlpCleanupSdkVersionMin;
  public static final GservicesValue<String> nlpCleanupUrl;
  public static final GservicesValue<String> nlpCleanupUrlTestKeys;
  public static final GservicesValue<String> nlpPackageName;
  public static final GservicesValue<Integer> nlpReinstallSdkVersionMax;
  public static final GservicesValue<Integer> nlpReinstallSdkVersionMin;
  public static final GservicesValue<String> nlpSharedUserId;
  public static final GservicesValue<String> optionalPermissionBucketsLearnMoreLink;
  public static final GservicesValue<String> optionalPermissionsLearnMoreLink;
  public static final GservicesValue<Boolean> otherOptionalPermissionsOnlyShowDangerous;
  public static final GservicesValue<Long> outstandingNotificationTimeDelayMs;
  public static final GservicesValue<Integer> passwordMaxFailedAttempts;
  public static final GservicesValue<String> passwordRecoveryUrl;
  public static final GservicesValue<String> peoplePageWarmWelcomeButtonIconUrl;
  public static final GservicesValue<String> peoplePageWarmWelcomeGraphicUrl;
  public static final GservicesValue<String> permissionBucketsLearnMoreLink;
  public static final GservicesValue<Integer> placesApiBiasRadiusMeters;
  public static final GservicesValue<String> placesApiKey;
  public static GservicesValue<Long> platformAntiMalwareDialogDelayMs;
  public static GservicesValue<Boolean> platformAntiMalwareEnabled;
  public static final GservicesValue<String> playGamesDocId;
  public static final GservicesValue<Integer> playGamesGmsCoreMinVersion;
  public static final GservicesValue<Long> playGamesInstallSuggestionFirstBackoffMs;
  public static final GservicesValue<Integer> playGamesInstallSuggestionMaxShownCount;
  public static final GservicesValue<Boolean> playGamesInstallSuggestionOnlyWhenGameFeatures;
  public static final GservicesValue<Long> playGamesInstallSuggestionSubsequentBackoffMs;
  public static final GservicesValue<Long> playLogDelayBetweenUploadsMs;
  public static final GservicesValue<Long> playLogImpressionSettleTimeMs;
  public static final GservicesValue<Long> playLogMaxStorageSize;
  public static final GservicesValue<Long> playLogMinDelayBetweenUploadsMs;
  public static final GservicesValue<Long> playLogRecommendedFileSize;
  public static final GservicesValue<String> playLogServerUrl;
  public static final GservicesValue<Integer> positiveRateThreshold;
  public static final GservicesValue<Boolean> postPurchaseSharingEnabled;
  public static final GservicesValue<Boolean> prePurchaseSharingEnabled;
  public static final GservicesValue<Long> preregistrationExpireAfterAcknowledgeMs;
  public static final GservicesValue<String> preregistrationForceList;
  public static final GservicesValue<Integer> preserveForwardLockApiMax;
  public static final GservicesValue<Integer> preserveForwardLockApiMin;
  public static final GservicesValue<Boolean> preventTabPreloadingOnHomePage = GservicesValue.value("finsky.prevent_tab_preloading_on_home_page", Boolean.valueOf(false));
  public static final GservicesValue<String> promptForFopSnoozeScheduleM;
  public static final GservicesValue<String> promptForFopSnoozeScheduleM2;
  public static final GservicesValue<String> rapidAutoUpdateListing;
  public static final GservicesValue<Integer> rapidAutoUpdateTosMinVersion;
  public static GservicesValue<String> readBookUrl;
  public static GservicesValue<String> reauthApiAccountManagerKey;
  public static GservicesValue<String> reauthApiAuthTokenType;
  public static GservicesValue<String> reauthApiGetSettingsEndpoint;
  public static GservicesValue<String> reauthApiVerifyCredentialsEndpoint;
  public static final GservicesValue<Long> recentlyUpdatedWindowSizeMs;
  public static final GservicesValue<Long> recommendationTtlMs;
  public static final GservicesValue<Long> recommendationsFetchTimeoutMs;
  public static final GservicesValue<Integer> recommendationsWidgetFlipIntervalMs;
  public static GservicesValue<Integer> recsCacheSizeMb;
  public static GservicesValue<String> redeemTermsAndConditionsUrl;
  public static final GservicesValue<Boolean> reducedBillingAddressRequiresPhonenumber;
  public static final GservicesValue<Integer> searchSuggestThrottleIntervalMs;
  public static final GservicesValue<Boolean> setupWizardAdditionalAccountVpaEnable;
  public static final GservicesValue<Long> setupWizardEarlyUpdateDeadlockMaxMs;
  public static final GservicesValue<Boolean> setupWizardEarlyUpdateEnable;
  public static GservicesValue<Boolean> setupWizardForceResizeForKeyboardInFullscreen;
  public static final GservicesValue<String> setupWizardPaymentHeaderBlueGraphicUrl;
  public static final GservicesValue<String> setupWizardPaymentHeaderWideBlueGraphicUrl;
  public static final GservicesValue<String> setupWizardRestoreFinalHoldBlueHeaderTabletUrl;
  public static final GservicesValue<String> setupWizardRestoreFinalHoldBlueHeaderUrl;
  public static final GservicesValue<String> setupWizardRestoreFinalHoldHeaderBlueLandscapeUrl;
  public static final GservicesValue<Long> setupWizardRestoreFinalHoldLongMs;
  public static final GservicesValue<Long> setupWizardRestoreFinalHoldShortMs;
  public static final GservicesValue<String> setupWizardRestoreHeaderBlueGraphicUrl;
  public static final GservicesValue<String> setupWizardRestoreWideHeaderBlueGraphicUrl;
  public static GservicesValue<Boolean> showMyAccountNewsstandsMessage;
  public static final GservicesValue<Boolean> showPackageRestoreNotifications;
  public static final GservicesValue<Boolean> skipAutoUpdateCleanupClientVersionCheck;
  public static final GservicesValue<Boolean> subscriptionsEnabled;
  public static final GservicesValue<String> supportUrl;
  public static final GservicesValue<String> supportedAccountTypes;
  public static final GservicesValue<String> surveySiteIdOverallApp;
  public static final GservicesValue<String> surveySiteIdSearchResults;
  public static final GservicesValue<String> surveySiteIdSearchResultsControlGroup;
  public static final GservicesValue<Boolean> systemAlertWindowPolicy2;
  public static final GservicesValue<String> systemAlertWindowPolicyTargets;
  public static final GservicesValue<Integer> tabskyMinVersion;
  public static final GservicesValue<String> targetsSdk23Whitelist;
  public static final GservicesValue<Long> unsubmittedReviewLifespanMs;
  public static GservicesValue<Boolean> userCheckForSelfUpdateEnabled;
  public static final GservicesValue<String> vendingAddressServerUrl;
  public static final GservicesValue<Long> vendingAlarmExpirationTimeoutMs;
  public static final GservicesValue<Long> vendingAlarmMaxTimeoutMs;
  public static final GservicesValue<Long> vendingAlarmMinTimeoutMs;
  public static GservicesValue<String> vendingAuthTokenType;
  public static final GservicesValue<Long> vendingBillingCountriesRefreshMs;
  public static final GservicesValue<Integer> vendingContentRating;
  public static final GservicesValue<Boolean> vendingHideContentRating;
  public static final GservicesValue<Integer> vendingRequestTimeoutMs;
  public static GservicesValue<String> vendingSecureAuthTokenType;
  public static GservicesValue<Float> verifyAppsBackoffMultiplier;
  public static GservicesValue<Boolean> verifyAppsLogToClearcut;
  public static GservicesValue<Boolean> verifyAppsLogUserDecisionToCsdServer;
  public static GservicesValue<Integer> verifyAppsMinimumGmsCoreVersionCodeForSharedId;
  public static GservicesValue<Integer> verifyAppsNumRetries;
  public static GservicesValue<Integer> verifyAppsTimeoutMs;
  public static GservicesValue<Float> verifyAppsUserDecisionBackoffMultiplier;
  public static GservicesValue<Integer> verifyAppsUserDecisionNumRetries;
  public static GservicesValue<Integer> verifyAppsUserDecisionTimeoutMs;
  public static GservicesValue<Float> verifyInstalledPackagesBackoffMultiplier;
  public static GservicesValue<Boolean> verifyInstalledPackagesEnabled;
  public static GservicesValue<Long> verifyInstalledPackagesMinimumWaitMs;
  public static GservicesValue<Integer> verifyInstalledPackagesNumRetries;
  public static GservicesValue<Integer> verifyInstalledPackagesTimeoutMs;
  public static GservicesValue<Boolean> verifyInstalledPlayPackagesEnabled;
  public static GservicesValue<Float> verifySystemPackagesProbability;
  public static final GservicesValue<Integer> videoAppTrailerPlaybackMinVersion;
  public static final GservicesValue<Integer> volleyBufferPoolSizeKb;
  public static final GservicesValue<String> walletEscrowUrl;
  public static final GservicesValue<String> wearAutoUpdateWhitelist;
  public static final GservicesValue<Boolean> wearDailyHygieneEnable;
  public static final GservicesValue<Boolean> wearGmsUpdateEnabled;
  public static final GservicesValue<Boolean> wearGmsVersionDependencyEnabled;
  public static final GservicesValue<Long> wearNodeKeepTimeMs;
  public static final GservicesValue<Boolean> wearSelfUpdateEnabled;
  public static final GservicesValue<String> whitelistedPlacesApiCountries;
  
  static
  {
    experimentDefaultMainCacheSizeMb = GservicesValue.value("finsky.experiment_default_main_cache_size_mb", Integer.valueOf(4));
    imageCacheSizeMb = GservicesValue.value("finsky.image_cache_size_mb", Integer.valueOf(4));
    recsCacheSizeMb = GservicesValue.value("finsky.recs_cache_size_mb", Integer.valueOf(5));
    debugOptionsEnabled = GservicesValue.value("finsky.debug_options_enabled", Boolean.valueOf(false));
    userCheckForSelfUpdateEnabled = GservicesValue.value("finsky.user_check_for_self_update_enabled", Boolean.valueOf(true));
    debugLimitedUserState = GservicesValue.value("finsky.debug_limited_user_state", Boolean.valueOf(false));
    enableGaiaRecovery = GservicesValue.value("finsky.enable_gaia_recovery", Boolean.valueOf(true));
    gtvNavigationalSuggestEnabled = GservicesValue.value("finsky.gtv_navigational_suggestions_enabled", Boolean.valueOf(false));
    legalNoticeMenuTitleOverride = GservicesValue.value("finsky.extra_menu_item_title", "");
    legalNoticeMenuUrl = GservicesValue.value("finsky.extra_menu_item_url", "");
    gamesBrowseUrl = GservicesValue.value("finsky.games_browse_url", "home?c=3&cat=GAME");
    dfeLogsAdMobEnabled = GservicesValue.value("finsky.dfe_logs_admob_enabled", Boolean.valueOf(true));
    logsDispatchIntervalSeconds = GservicesValue.value("finsky.logs_dispatch_interval_seconds", Integer.valueOf(15));
    maxLogQueueSizeBeforeFlush = GservicesValue.value("finsky.maximum_log_queue_size", Integer.valueOf(40));
    vendingAuthTokenType = GservicesValue.value("vending.auth_token_type", "android");
    vendingSecureAuthTokenType = GservicesValue.value("vending.secure_auth_token_type", "androidsecure");
    redeemTermsAndConditionsUrl = GservicesValue.value("finsky.redeem_terms_and_conditions_url", "https://play.google.com/intl/%locale%/about/redeem-terms.html");
    enableCorpusWidgets = GservicesValue.value("finsky.enable_corpus_widgets", Boolean.valueOf(false));
    appsWidgetUrl = GservicesValue.value("finsky.widget_url", "promo?c=3");
    musicWidgetUrl = GservicesValue.value("finsky.music_widget_url", "promo?c=2");
    booksWidgetUrl = GservicesValue.value("finsky.books_widget_url", "promo?c=1");
    moviesWidgetUrl = GservicesValue.value("finsky.movies_widget_url", "promo?c=4");
    consumptionAppDataFilter = GservicesValue.value("finsky.consumption_app_data_filter", "");
    readBookUrl = GservicesValue.value("finsky.read_book_url", "https://play.google.com/books/reader");
    contentFilterInfoUrl = GservicesValue.value("finsky.content_filter_info_url", "http://www.google.com/support/androidmarket/bin/answer.py?answer=1075738");
    analyticsEnabled = GservicesValue.value("finsky.analytics_enabled", Boolean.valueOf(true));
    walletEscrowUrl = GservicesValue.value("finsky.wallet_escrow_url", "https://wallet.google.com/dehEfe");
    musicDmcaReportLink = GservicesValue.value("finsky.music_dmca_report_link", "https://www.google.com/support/artists?p=DMCA");
    permissionBucketsLearnMoreLink = GservicesValue.value("finsky.permission_buckets_learn_more_link", "https://support.google.com/googleplay/?p=app_permissions");
    optionalPermissionBucketsLearnMoreLink = GservicesValue.value("finsky.optional_permission_buckets_learn_more_link", "https://support.google.com/googleplay/?p=app_permissons_m");
    optionalPermissionsLearnMoreLink = GservicesValue.value("finsky.optional_permissions_learn_more_link", "https://support.google.com/googleplay/?p=app_permissons_m");
    otherOptionalPermissionsOnlyShowDangerous = GservicesValue.value("finsky.other_optional_permissions_only_show_dangerous", Boolean.valueOf(false));
    additionalRemovedPermissionsM = GservicesValue.value("finsky.additional_removed_permissions_m", "");
    alwaysUseOptionalPermissionBucketsM = GservicesValue.value("finsky.always_use_optional_permissions_buckets_m", Boolean.valueOf(true));
    gaiaOptOutLearnMoreLink = GservicesValue.value("finsky.gaia_opt_out_learn_more_link", "https://support.google.com/googleplay/answer/1626831");
    targetsSdk23Whitelist = GservicesValue.value("finsky.targets_sdk23_whitelist", "");
    systemAlertWindowPolicyTargets = GservicesValue.value("finsky.system_alert_window_policy_targets", "com.facebook.orca");
    systemAlertWindowPolicy2 = GservicesValue.value("finsky.system_alert_window_policy_2", Boolean.valueOf(false));
    initializeBillingDelayMs = GservicesValue.value("finsky.initialize_billing_delay_ms", Integer.valueOf(10000));
    authChallengeSessionDurationMs = GservicesValue.value("finsky.auth_challenge_session_duration_ms", Long.valueOf(1800000L));
    hasFopCacheTimeoutMs = GservicesValue.value("finsky.has_fop_cache_timeout_ms", Long.valueOf(604800000L));
    promptForFopSnoozeScheduleM = GservicesValue.value("finsky.prompt_for_fop_snooze_schedule_m", "10080");
    promptForFopSnoozeScheduleM2 = GservicesValue.value("finsky.prompt_for_fop_snooze_schedule_m2", "10080,20160,43200,-1");
    enableSensitiveLogging = GservicesValue.value("finsky.enable_sensitive_logging", Boolean.valueOf(false));
    enablePlayLogs = GservicesValue.value("finsky.enable_playlog", Boolean.valueOf(true));
    forcePostPurchaseCrossSell = GservicesValue.value("finsky.force_post_purchase_cross_sell", Boolean.valueOf(false));
    playLogMaxStorageSize = GservicesValue.value("finsky.playlog_max_storage_size_bytes", Long.valueOf(2097152L));
    playLogRecommendedFileSize = GservicesValue.value("finsky.playlog_recommended_file_size_bytes", Long.valueOf(32768L));
    playLogDelayBetweenUploadsMs = GservicesValue.value("finsky.playlog_delay_between_uploads_ms", Long.valueOf(300000L));
    playLogMinDelayBetweenUploadsMs = GservicesValue.value("finsky.playlog_min_delay_between_uploads_ms", Long.valueOf(60000L));
    playLogServerUrl = GservicesValue.value("finsky.play_log_server_url", "https://play.googleapis.com/play/log");
    playLogImpressionSettleTimeMs = GservicesValue.value("finsky.playlog_impression_settle_time_ms", Long.valueOf(2000L));
    vendingRequestTimeoutMs = GservicesValue.value("finsky.vending_request_timeout_ms", Integer.valueOf(20000));
    tabskyMinVersion = GservicesValue.value("finsky.tabsky_min_version", Integer.valueOf(110));
    volleyBufferPoolSizeKb = GservicesValue.value("finsky.volley_buffer_pool_size_kb", Integer.valueOf(256));
    reducedBillingAddressRequiresPhonenumber = GservicesValue.value("finsky.reduced_billing_address_requires_phonenumber", Boolean.valueOf(true));
    enableDcbReducedBillingAddress = GservicesValue.value("finsky.enable_dcb_reduced_billing_address", Boolean.valueOf(true));
    vendingAddressServerUrl = GservicesValue.value("vending_address_server_url", "http://i18napis.appspot.com/address");
    vendingBillingCountriesRefreshMs = GservicesValue.value("vending_billingcountries_refresh_ms", Long.valueOf(432000000L));
    vendingContentRating = GservicesValue.value("vending_content_rating", Integer.valueOf(4));
    vendingHideContentRating = GservicesValue.value("vending_hide_content_rating", Boolean.valueOf(false));
    dcb3VerifyAssociationRetries = GservicesValue.value("finsky.dcb3_verify_association_retries", Integer.valueOf(0));
    dcb3PrepareSendDeviceRebooted = GservicesValue.value("finsky.dcb3_prepare_send_device_rebooted", Boolean.valueOf(false));
    dcb3PassphraseKeyVersion = GservicesValue.value("finsky.dcb3_passphrase_key_version", Integer.valueOf(-1));
    vendingAlarmMaxTimeoutMs = GservicesValue.value("vending_alarm_max_timeout_ms", Long.valueOf(86400000L));
    vendingAlarmExpirationTimeoutMs = GservicesValue.value("vending_alarm_expiration_timeout_ms", Long.valueOf(604800000L));
    vendingAlarmMinTimeoutMs = GservicesValue.value("vending_alarm_min_timeout_ms", Long.valueOf(10000L));
    supportUrl = GservicesValue.value("finsky.support_url", "https://support.google.com/googleplay/digital-content/#topic=3364261");
    helpCenterBackgroundDataUrl = GservicesValue.value("finsky.support_enable_background_data_url", "https://support.google.com/googleplay/answer/1663315");
    helpCenterManagingSubscriptionsUrl = GservicesValue.value("finsky.support_subscriptions_on_google_play", "https://support.google.com/googleplay/answer/2476088");
    editPaymentMethodUrl = GservicesValue.value("finsky.support_edit_payment_method_url", "https://payments.google.com/manage/paymentMethods");
    postPurchaseSharingEnabled = GservicesValue.value("finsky.post_purchase_sharing_enabled", Boolean.valueOf(true));
    prePurchaseSharingEnabled = GservicesValue.value("finsky.pre_purchase_sharing_enabled", Boolean.valueOf(true));
    launchUrlsEnabled = GservicesValue.value("finsky.launch_urls_enabled", Boolean.valueOf(true));
    externalReferrerInstallOrganic = GservicesValue.value("finsky.external_referrer_install_organic", "utm_source%3Dgoogle_play%26utm_medium%3Dorganic");
    externalReferrerInstallDeepLink = GservicesValue.value("finsky.external_referrer_install_deep_link", "utm_source%3Dreferrer_missing%26utm_medium%3Dreferrer_missing");
    externalReferrerLifespanMs = GservicesValue.value("finsky.external_referrer_lifespan_ms", Long.valueOf(7776000000L));
    subscriptionsEnabled = GservicesValue.value("finsky.subscriptions_enabled", Boolean.valueOf(true));
    enableThirdPartyInlineAppInstalls = GservicesValue.value("finsky.enable_third_party_inline_app_installs", Boolean.valueOf(false));
    logInlineAppInstallReferrerEnabled = GservicesValue.value("finsky.log_inline_app_install_referrer_enabled", Boolean.valueOf(true));
    enableThirdPartyDirectPurchases = GservicesValue.value("finsky.enable_third_party_direct_purchases", Boolean.valueOf(false));
    enableThirdPartyDetailsApi = GservicesValue.value("finsky.enable_third_party_details_api", Boolean.valueOf(false));
    enableDetailsApi = GservicesValue.value("finsky.enable_details_api", Boolean.valueOf(false));
    dailyHygienePreloadExperiments = GservicesValue.value("finsky.daily_hygiene_preload_experiments", Boolean.valueOf(false));
    dailyHygieneRegularIntervalMs = GservicesValue.value("finsky.daily_hygiene_regular_interval_ms", Long.valueOf(86400000L));
    dailyHygieneRetryIntervalMs = GservicesValue.value("finsky.daily_hygiene_retry_interval_ms", Long.valueOf(600000L));
    dailyHygieneBootDelayMs = GservicesValue.value("finsky.daily_hygiene_boot_delay_ms", Long.valueOf(30000L));
    dailyHygieneImmediateDelayMs = GservicesValue.value("finsky.daily_hygiene_immediate_delay_ms", Long.valueOf(1000L));
    dailyHygieneJitterFactor = GservicesValue.value("finsky.daily_hygiene_reschedule_jitter_factor", Float.valueOf(0.1F));
    dailyHygieneInitialJitterFactor = GservicesValue.value("finsky.daily_hygiene_initial_reschedule_jitter_factor", Float.valueOf(0.5F));
    dailyHygieneProvisionHoldoffMaxMs = GservicesValue.value("finsky.daily_hygiene_provision_holdoff_max_ms", Long.valueOf(82800000L));
    dailyHygieneHoldoffIntervalMs = GservicesValue.value("finsky.daily_hygiene_holdoff_interval_ms", Long.valueOf(60000L));
    dailyHygieneHoldoffDuringSelfUpdate = GservicesValue.value("finsky.daily_hygiene_holdoff_during_self_update", Boolean.valueOf(false));
    dailyHygieneImmediateRunVersionCodeLow = GservicesValue.value("finsky.daily_hygiene_emergency_version_code_low", Integer.valueOf(-1));
    dailyHygieneImmediateRunVersionCodeHigh = GservicesValue.value("finsky.daily_hygiene_emergency_version_code_high", Integer.valueOf(-1));
    autoUpdateDeliveryHoldoffMs = GservicesValue.value("finsky.auto_update_delivery_holdoff_ms", Long.valueOf(300000L));
    continueUrlExpirationMs = GservicesValue.value("finsky.continue_url_expiration_ms", Long.valueOf(1200000L));
    autoUpdateExcludeForegroundServices = GservicesValue.value("finsky.auto_update_exclude_foreground_services", Boolean.valueOf(true));
    autoUpdateExcludeRunningPackagesPre = GservicesValue.value("finsky.auto_update_exclude_running_packages_pre", Boolean.valueOf(true));
    gmsCoreAutoUpdateEnabled = GservicesValue.value("finsky.play_services_auto_update_enabled", Boolean.valueOf(true));
    gmsCoreAutoUpdateProjectionHoldoff = GservicesValue.value("finsky.gms_core_auto_update_projection_holdoff", Boolean.valueOf(true));
    eduDevicePolicyApp = GservicesValue.value("finsky.edu_device_policy_package_name", "com.google.android.apps.enterprise.dmagent");
    nlpSharedUserId = GservicesValue.value("finsky.nlp_shared_user_id", "");
    nlpPackageName = GservicesValue.value("finsky.nlp_package_name", "com.google.android.location");
    nlpReinstallSdkVersionMin = GservicesValue.value("finsky.nlp_reinstall_sdk_min", Integer.valueOf(9));
    nlpReinstallSdkVersionMax = GservicesValue.value("finsky.nlp_reinstall_sdk_max", Integer.valueOf(15));
    nlpCleanupConfigurationId = GservicesValue.value("finsky.nlp_cleanup_configuration_id", Integer.valueOf(0));
    nlpCleanupFlagsMask = GservicesValue.value("finsky.nlp_cleanup_flags_mask", Integer.valueOf(129));
    nlpCleanupFlagsSet = GservicesValue.value("finsky.nlp_cleanup_flags_set", Integer.valueOf(129));
    nlpCleanupSdkVersionMin = GservicesValue.value("finsky.nlp_cleanup_sdk_min", Integer.valueOf(16));
    nlpCleanupSdkVersionMax = GservicesValue.value("finsky.nlp_cleanup_sdk_max", Integer.valueOf(16));
    nlpCleanupNlpVersionMin = GservicesValue.value("finsky.nlp_cleanup_nlp_min", Integer.valueOf(1110));
    nlpCleanupNlpVersionMax = GservicesValue.value("finsky.nlp_cleanup_nlp_max", Integer.valueOf(1110));
    nlpCleanupExpectedSignature = GservicesValue.value("finsky.nlp_cleanup_expected_signature", "OJGKRT0HGZNU-LGa8F7GViztV4g");
    nlpCleanupExpectedSignatureTestKeys = GservicesValue.value("finsky.nlp_cleanup_expected_signature_test_keys", "WOHEEz90Qew9LCcCcKFIAtpHug4");
    nlpCleanupUrl = GservicesValue.value("finsky.nlp_cleanup_url", "https://ssl.gstatic.com/android/market_images/apks/nlpfixer/nlpfixer-r01.apk");
    nlpCleanupCookieName = GservicesValue.value("finsky.nlp_cleanup_cookie_name", "");
    nlpCleanupCookieValue = GservicesValue.value("finsky.nlp_cleanup_cookie_value", "");
    nlpCleanupUrlTestKeys = GservicesValue.value("finsky.nlp_cleanup_url_test_keys", "https://ssl.gstatic.com/android/market_images/apks/nlpfixer/nlpfixer-r01-test-keys.apk");
    nlpCleanupCookieNameTestKeys = GservicesValue.value("finsky.nlp_cleanup_cookie_name_test_keys", "");
    nlpCleanupCookieValueTestKeys = GservicesValue.value("finsky.nlp_cleanup_cookie_value_test_keys", "");
    nlpCleanupDowngradeFlag = GservicesValue.value("finsky.nlp_cleanup_downgrade_flag", Boolean.valueOf(false));
    nlpCleanupLogCommonStatuses = GservicesValue.value("finsky.nlp_cleanup_log_common_statuses", Boolean.valueOf(false));
    downloadBytesOverMobileRecommended = GservicesValue.value("finsky.download_bytes_mobile_recommended", Long.valueOf(52428800L));
    downloadBytesOverMobileMaximum = GservicesValue.value("finsky.download_bytes_mobile_maximum", Long.valueOf(9223372036854775807L));
    downloadFreeSpaceThresholdBytes = GservicesValue.value("finsky.download_free_space_threshold_bytes", Long.valueOf(-1L));
    downloadFreeSpaceApkSizeFactor = GservicesValue.value("finsky.download_free_space_apk_size_factor", Integer.valueOf(100));
    downloadSendBaseVersionCode = GservicesValue.value("finsky.download_send_base_version", Boolean.valueOf(true));
    deliveryDataExpirationMs = GservicesValue.value("finsky.download_deliverydata_expiration", Long.valueOf(14400000L));
    downloadPatchFreeSpaceFactor = GservicesValue.value("finsky.download_patch_free_space_factor", Integer.valueOf(210));
    downloadExternalFileSizeMinBytes = GservicesValue.value("finsky.download_external_file_size_min_bytes", Long.valueOf(52428800L));
    downloadExternalFreeSpaceFactor = GservicesValue.value("finsky.download_external_free_space_factor", Integer.valueOf(200));
    downloadExternalFreeSpaceThresholdBytes = GservicesValue.value("finsky.download_external_free_space_threshold_bytes", Long.valueOf(67108864L));
    preserveForwardLockApiMin = GservicesValue.value("finsky.preserve_forward_lock_api_min", Integer.valueOf(16));
    preserveForwardLockApiMax = GservicesValue.value("finsky.preserve_forward_lock_api_max", Integer.valueOf(19));
    appRestoreHoldoffMs = GservicesValue.value("finsky.app_restore_holdoff_ms", Long.valueOf(120000L));
    appRestoreFailsafeMs = GservicesValue.value("finsky.app_restore_failsafe_ms", Long.valueOf(600000L));
    appRestoreFetchListMaxAttempts = GservicesValue.value("finsky.app_restore_fetch_list_max_attempts", Integer.valueOf(4));
    appRestoreRetryFetchListHoldoffMs = GservicesValue.value("finsky.app_restore_retry_fetch_list_holdoff_ms", Long.valueOf(120000L));
    appRestoreDownloadMaxAttempts = GservicesValue.value("finsky.app_restore_download_max_attempts", Integer.valueOf(4));
    appRestoreRetryDownloadHoldoffMs = GservicesValue.value("finsky.app_restore_retry_download_holdoff_ms", Long.valueOf(240000L));
    appRestoreRetryDownloadHoldoffHighPriorityMs = GservicesValue.value("finsky.app_restore_retry_download_holdoff_high_priority_ms", Long.valueOf(30000L));
    appRestoreHttpStatusBlacklist = GservicesValue.value("finsky.app_restore_retry_download_blacklist", "198,498");
    appRestoreAppIconMaxAttempts = GservicesValue.value("finsky.app_restore_app_icon_max_attempts", Integer.valueOf(4));
    myLibraryWidgetInteractionClusterMs = GservicesValue.value("finsky.my_library_widget_interactions_cluster_ms", Long.valueOf(1000L));
    myLibraryWidgetShorttermDurationMs = GservicesValue.value("finsky.my_library_widget_shortterm_duration_ms", Long.valueOf(86400000L));
    myLibraryWidgetMidtermDurationMs = GservicesValue.value("finsky.my_library_widget_midterm_duration_ms", Long.valueOf(604800000L));
    myLibraryWidgetImportantContributionFraction = GservicesValue.value("finsky.my_library_widget_important_contribution_fraction", Float.valueOf(0.2F));
    myLibraryWidgetShorttermDecay = GservicesValue.value("finsky.my_library_widget_shortterm_decay", Float.valueOf(0.8F));
    myLibraryWidgetHasContentScoreMap = GservicesValue.value("finsky.my_library_has_content_scores", "0:15");
    myLibraryWidgetShorttermScores = GservicesValue.value("finsky.my_library_widget_shortterm_scores", "0:5");
    myLibraryWidgeMidtermScores = GservicesValue.value("finsky.my_library_widget_midterm_scores", "0:1");
    myLibraryWidgetAlwaysIncludeMostRecentBackend = GservicesValue.value("finsky.my_library_widget_always_include_most_recent", Boolean.valueOf(true));
    recommendationsWidgetFlipIntervalMs = GservicesValue.value("finsky.recs_widget_flip_interval_ms", Integer.valueOf(-1));
    consumptionAppTimeoutMs = GservicesValue.value("finsky.consumption_app_timeout_ms", Long.valueOf(7000L));
    consumptionAppImageTimeoutMs = GservicesValue.value("finsky.consumption_app_image_timeout_ms", Long.valueOf(5000L));
    recommendationsFetchTimeoutMs = GservicesValue.value("finsky.recommendations_fetch_timeout_ms", Long.valueOf(15000L));
    minimumVideosVersionCodePreHoneycomb = GservicesValue.value("finsky.minimum_videos_app_version_code_pre_honeycomb", Integer.valueOf(2009));
    minimumVideosVersionCodeHoneycombPlus = GservicesValue.value("finsky.minimum_videos_app_version_code_post_honeycomb", Integer.valueOf(20090));
    minimumMusicVersionCode = GservicesValue.value("finsky.minimum_music_app_version_code", Integer.valueOf(1409));
    minimumNumberOfRecs = GservicesValue.value("finsky.minimum_number_of_recommendations", Integer.valueOf(4));
    recommendationTtlMs = GservicesValue.value("finsky.recommendation_ttl_ms", Long.valueOf(172800000L));
    gaiaAuthValidityMs = GservicesValue.value("finsky.gaia_auth_validity_ms", Long.valueOf(0L));
    platformAntiMalwareEnabled = GservicesValue.value("finsky.platform_anti_malware_enabled", Boolean.valueOf(true));
    antiMalwareConsentRequired = GservicesValue.value("finsky.anti_malware_consent_required", Boolean.valueOf(true));
    platformAntiMalwareDialogDelayMs = GservicesValue.value("finsky.platform_anti_malware_dialog_delay_ms", Long.valueOf(3600000L));
    antiMalwareActivityEnabled = GservicesValue.value("finsky.anti_malware_activity_enabled", Boolean.valueOf(true));
    verifyInstalledPackagesMinimumWaitMs = GservicesValue.value("finsky.verify_installed_packages_minimum_wait_time_ms", Long.valueOf(518400000L));
    verifyInstalledPackagesTimeoutMs = GservicesValue.value("finsky.verify_installed_packages_timeout_ms", Integer.valueOf(15000));
    verifyInstalledPackagesNumRetries = GservicesValue.value("finsky.verify_installed_packages_retries", Integer.valueOf(8));
    verifyInstalledPackagesBackoffMultiplier = GservicesValue.value("finsky.verify_installed_packages_backoff_multiplier", Float.valueOf(2.0F));
    verifyAppsTimeoutMs = GservicesValue.value("finsky.verify_apps_timeout_ms", Integer.valueOf(3000));
    verifyAppsNumRetries = GservicesValue.value("finsky.verify_apps_retries", Integer.valueOf(3));
    verifyAppsBackoffMultiplier = GservicesValue.value("finsky.verify_apps_backoff_multiplier", Float.valueOf(1.0F));
    verifyAppsUserDecisionTimeoutMs = GservicesValue.value("finsky.verify_apps_user_decision_timeout_ms", Integer.valueOf(15000));
    verifyAppsUserDecisionNumRetries = GservicesValue.value("finsky.verify_apps_user_decision_retries", Integer.valueOf(8));
    verifyAppsUserDecisionBackoffMultiplier = GservicesValue.value("finsky.verify_apps_user_decision_backoff_multiplier", Float.valueOf(2.0F));
    verifyInstalledPackagesEnabled = GservicesValue.value("finsky.verify_installed_packages_enabled", Boolean.valueOf(true));
    verifyInstalledPlayPackagesEnabled = GservicesValue.value("finsky.verify_installed_play_packages_enabled", Boolean.valueOf(true));
    verifySystemPackagesProbability = GservicesValue.value("finsky.verify_system_packages_probability", Float.valueOf(0.1F));
    verifyAppsMinimumGmsCoreVersionCodeForSharedId = GservicesValue.value("finsky.verify_apps_minimum_gms_core_version_code_for_shared_id", Integer.valueOf(7600000));
    verifyAppsLogToClearcut = GservicesValue.value("finsky.verify_apps_log_to_clearcut", Boolean.valueOf(false));
    verifyAppsLogUserDecisionToCsdServer = GservicesValue.value("finsky.verify_apps_log_user_decision_to_csd_server", Boolean.valueOf(true));
    enableReviewComments = GservicesValue.value("finsky.enable_review_comments", Boolean.valueOf(true));
    enableRemoveAppsFromLibrary = GservicesValue.value("finsky.enable_remove_apps_from_library", Boolean.valueOf(true));
    iabV3SubscriptionsEnabled = GservicesValue.value("finsky.iabv3_subscriptions_enabled", Boolean.valueOf(true));
    iabV3MaxPurchasesInResponse = GservicesValue.value("finsky.iabv3_max_purchases_in_response", Integer.valueOf(100));
    iabV3NetworkTimeoutMs = GservicesValue.value("finsky.iabv3_network_timeout_ms", Long.valueOf(20000L));
    iabV3SkuDetailsMaxSize = GservicesValue.value("finsky.iabv3_sku_details_max_size", Integer.valueOf(20));
    iabV3FirstPartyApiEnabled = GservicesValue.value("finsky.iabv3_first_party_api_enabled", Boolean.valueOf(true));
    iabV3FirstPartyApiUnrestrictedAccess = GservicesValue.value("finsky.iabv3_first_party_api_unrestricted_access", Boolean.valueOf(false));
    placesApiBiasRadiusMeters = GservicesValue.value("finsky.places_api_bias_radius_meters", Integer.valueOf(50000));
    whitelistedPlacesApiCountries = GservicesValue.value("finsky.whitelisted_places_api_countries", "0:CA,CH,US");
    placesApiKey = GservicesValue.value("finsky.places_api_key", "AIzaSyCsc46SHdb57jPJa9fo7euV_HBDgwdrXsE");
    enablePeopleSuggestWidget = GservicesValue.value("finsky.enable_people_suggest_widget", Boolean.valueOf(true));
    lightPurchaseAutoDismissMs = GservicesValue.value("finsky.light_purchase_auto_dismiss_ms", Long.valueOf(2500L));
    defaultPurchaseAuthentication = GservicesValue.value("finsky.default_purchase_authentication", Integer.valueOf(2));
    passwordRecoveryUrl = GservicesValue.value("finsky.password_recovery_url", "https://accounts.google.com/RecoverAccount?fpOnly=1&Email=%email%");
    passwordMaxFailedAttempts = GservicesValue.value("finsky.password_max_failed_attempts", Integer.valueOf(5));
    maxAutoUpdateDialogShownCount = GservicesValue.value("finsky.max_times_auto_update_cleanup_shown", Integer.valueOf(3));
    autoUpdateDialogFirstBackoffDays = GservicesValue.value("finsky.auto_update_cleanup_first_backoff_days", Integer.valueOf(7));
    autoUpdateDialogSecondBackoffDays = GservicesValue.value("finsky.auto_update_cleanup_second_backoff_days", Integer.valueOf(23));
    autoUpdateDialogSubsequentBackoffDays = GservicesValue.value("finsky.auto_update_cleanup_subsequent_backoff_days", Integer.valueOf(-1));
    skipAutoUpdateCleanupClientVersionCheck = GservicesValue.value("finsky.skip_auto_update_cleanup_client_version_check", Boolean.valueOf(false));
    playGamesInstallSuggestionMaxShownCount = GservicesValue.value("finsky.play_games_install_suggestion_max_times_shown", Integer.valueOf(0));
    playGamesGmsCoreMinVersion = GservicesValue.value("finsky.play_games_gms_core_min_version", Integer.valueOf(3150000));
    playGamesInstallSuggestionOnlyWhenGameFeatures = GservicesValue.value("finsky.play_games_install_suggestion_only_when_game_features", Boolean.valueOf(false));
    playGamesInstallSuggestionFirstBackoffMs = GservicesValue.value("finsky.play_games_install_suggestion_first_backoff_ms", Long.valueOf(604800000L));
    playGamesInstallSuggestionSubsequentBackoffMs = GservicesValue.value("finsky.play_games_install_suggestion_subsequent_backoff_ms", Long.valueOf(2592000000L));
    playGamesDocId = GservicesValue.value("finsky.play_games_doc_id", "com.google.android.play.games");
    enableSessionStatsLog = GservicesValue.value("finsky.enable_session_stats_log", Boolean.valueOf(true));
    musicAppSubscriptionBackendDocidBlacklist = GservicesValue.value("finsky.music_app_subscription_backend_docid_blacklist", "Saeaaaaaa");
    musicAllAccessSubscriptionBackendDocid = GservicesValue.value("finsky.all_access_backend_docid", "Saeaaaaaa");
    musicAppSubscriptionResignupEnabled = GservicesValue.value("finsky.music_app_subscription_resignup_enabled", Boolean.valueOf(false));
    additionalTargets = GservicesValue.value("finsky.additional_targets", null);
    recentlyUpdatedWindowSizeMs = GservicesValue.value("finsky.recently_updated_window_size_ms", Long.valueOf(259200000L));
    outstandingNotificationTimeDelayMs = GservicesValue.value("finsky.outstanding_notification_time_delay_ms", Long.valueOf(259200000L));
    corpusAwarenessThresholdBooks = GservicesValue.value("finsky.corpusAwarenessThreshold.books", Integer.valueOf(6));
    corpusAwarenessThresholdMagazines = GservicesValue.value("finsky.corpusAwarenessThreshold.magazines", Integer.valueOf(6));
    corpusAwarenessThresholdMovies = GservicesValue.value("finsky.corpusAwarenessThreshold.movies", Integer.valueOf(1));
    corpusAwarenessThresholdMusic = GservicesValue.value("finsky.corpusAwarenessThreshold.music", Integer.valueOf(6));
    autoUpdateBroadcastDebouncerDelayMs = GservicesValue.value("finsky.auto_update_broadcast_debouncer_delay", Long.valueOf(3000L));
    autoUpdateBroadcastStabilizerDelayMs = GservicesValue.value("finsky.auto_update_broadcast_stabilizer_delay", Long.valueOf(180000L));
    autoUpdateThrottleIntervalMs = GservicesValue.value("finsky.auto_update_throttle_interval", Long.valueOf(3600000L));
    autoUpdateSkipPowerCheckIntervalMs = GservicesValue.value("finsky.auto_update_skip_power_check_interval", Long.valueOf(259200000L));
    autoUpdateWifiCheckIntervalMs = GservicesValue.value("finsky.auto_update_wifi_check_interval", Long.valueOf(3600000L));
    enableAutoUpdatePowerAndWifiBroadcastListener = GservicesValue.value("finsky.enable_auto_update_power_broadcast_listener", Boolean.valueOf(false));
    autoUpdateGearheadCheckIntervalMs = GservicesValue.value("finsky.auto_update_gearhead_check_interval", Long.valueOf(3600000L));
    autoUpdateJobSchedulerGearheadTimeoutMs = GservicesValue.value("finsky.auto_update_job_scheduler_gearhead_delay", Long.valueOf(604800000L));
    autoUpdateJobSchedulerMaxTimeoutMs = GservicesValue.value("finsky.auto_update_job_scheduler_timeout_ms", Long.valueOf(82800000L));
    autoUpdateJobSchedulerMinTimeoutMs = GservicesValue.value("finsky.auto_update_job_scheduler_min_timeout_ms", Long.valueOf(120000L));
    videoAppTrailerPlaybackMinVersion = GservicesValue.value("finsky.video_app_trailer_playback_min_version", Integer.valueOf(27030));
    firstNewsstandAppVersion = GservicesValue.value("finsky.newsstand_app_first_version", Integer.valueOf(132340703));
    newsstandFreeSubscriptionCompletionAppVersion = GservicesValue.value("finsky.newsstand_free_subscription_completion_version", Integer.valueOf(2015020408));
    newsstandFreeSampleMagazinesAppVersion = GservicesValue.value("finsky.newsstand_free_sample_magazines_version", Integer.valueOf(2015030108));
    gelPackageName = GservicesValue.value("finsky.gel_package_name", "com.google.android.googlequicksearchbox");
    libraryReplicatorRescheduleDelayMs = GservicesValue.value("finsky.library_replicator_reschedule_delay_ms", Integer.valueOf(1000));
    positiveRateThreshold = GservicesValue.value("finsky.positive_rate_threshold", Integer.valueOf(3));
    peoplePageWarmWelcomeGraphicUrl = GservicesValue.value("finsky.peoplePageWarmWelcomeGraphicUrl", "https://lh6.ggpht.com/MBGKEdyM2S9-d0wZxNGZkdrTDHeT6iU3fANSMYh6R8cw6GNlRoEi_pMzxoZhJTLl4A");
    peoplePageWarmWelcomeButtonIconUrl = GservicesValue.value("finsky.peoplePageWarmWelcomeButtonIconUrl", "https://lh3.ggpht.com/UFLxPwW24-zpdw50aPXy07XUncvFN7BT4LW0yIKB6uNWWljHiiWalKAddBUHl15cgmg");
    setupWizardRestoreHeaderBlueGraphicUrl = GservicesValue.value("finsky.setupWizardRestoreHeaderBlueGraphicUrl", "https://lh3.ggpht.com/1ekRt1ToFJPlPrDmTUbaWcD8HtQxQk_KEp8l8-FZXbRnzdQaR-rrzn3xo250k9S1epc");
    setupWizardRestoreWideHeaderBlueGraphicUrl = GservicesValue.value("finsky.setupWizardRestoreWideHeaderBlueGraphicUrl", "https://lh3.ggpht.com/0CsFZStY7DZrq_SXIMl8wcPSgvs3OESY6m30Ae8MrQnX5UnwWqo6hMTClDAgrWUzA7n_YQ");
    setupWizardRestoreFinalHoldBlueHeaderUrl = GservicesValue.value("finsky.setupWizardRestoreFinalHoldBlueHeaderUrl", "https://lh3.ggpht.com/SvoAUkpx064vMnO5VnDaXJYNYGojPIsijFUq0enaXckHjvSMHNnSP85oVlRTRMZzGte7");
    setupWizardRestoreFinalHoldHeaderBlueLandscapeUrl = GservicesValue.value("finsky.setupWizardRestoreFinalHoldHeaderBlueLandscapeUrl", "https://lh3.ggpht.com/mq8qQcSnAeXJTpM52HHnnD79s4bEshlT3vKbS5uNl9Lie_TwtfhhFXrJ7XTCG_FptaTN");
    setupWizardRestoreFinalHoldBlueHeaderTabletUrl = GservicesValue.value("finsky.setupWizardRestoreFinalHoldBlueHeaderTabletUrl", "https://lh3.ggpht.com/aARRX4T1er_Y3-Q3O9IOI-UyVo-otrCq8wkeNvQiD4k-v_b3OJonycdeK-ttWool3I4");
    setupWizardRestoreFinalHoldShortMs = GservicesValue.value("finsky.setup_wizard_restore_final_hold_short_ms", Long.valueOf(60000L));
    setupWizardRestoreFinalHoldLongMs = GservicesValue.value("finsky.setup_wizard_restore_final_hold_long_ms", Long.valueOf(180000L));
    setupWizardAdditionalAccountVpaEnable = GservicesValue.value("finsky.setup_wizard_additional_account_vpa_enable", Boolean.valueOf(true));
    setupWizardPaymentHeaderBlueGraphicUrl = GservicesValue.value("finsky.setupWizardPaymentHeaderBlueGraphicUrl", "https://lh3.ggpht.com/5FYtYy0wEOSW0FXswusE7s2_gicFCwm1ngI-7odbhsNCkTGI5S6Jk6FWtGOjkPgmPhXIkw");
    setupWizardPaymentHeaderWideBlueGraphicUrl = GservicesValue.value("finsky.setupWizardPaymentHeaderWideBlueGraphicUrl", "https://lh3.ggpht.com/WqCZKwL-R3IQhxcyzDEYPKLEwTjc_UV42J4okAm3dEVKm0ktJb7kFcfaJA7DBU9pPNMw");
    setupWizardForceResizeForKeyboardInFullscreen = GservicesValue.value("finsky.setupWizardForceResizeForKeyboardInFullscreen", Boolean.valueOf(true));
    clientMutationCacheCirclesModelCacheSize = GservicesValue.value("finsky.client_mutation_cache_circles_model_cache_size", Integer.valueOf(100));
    myLibraryWidgetBackgroundImageLocation = GservicesValue.value("finsky.myLibraryWidget.backgroundImageLocation", "/system/media/play_widget_background.png");
    musicAllAccessSignUpIntentUrl = GservicesValue.value("finsky.music_all_access_sign_up_intent_url", "http://play.google.com/music/listen?signup=1&utm_source=playstore&utm_medium=album_detail_page&utm_campaign=30daytrial");
    musicArtistRadioIntentUrl = GservicesValue.value("finsky.music_artist_radio_intent_url", "https://play.google.com/music/r/m/%artistId%?play=1&welcome=0&utm_source=playstore&utm_campaign=artist_play_button");
    setupWizardEarlyUpdateEnable = GservicesValue.value("finsky.setup_wizard_early_update_enable", Boolean.valueOf(true));
    setupWizardEarlyUpdateDeadlockMaxMs = GservicesValue.value("finsky.setup_wizard_early_update_deadlock_max_ms", Long.valueOf(5000L));
    unsubmittedReviewLifespanMs = GservicesValue.value("finsky.unsubmitted_reviews_max_lifespan_ms", Long.valueOf(2592000000L));
    supportedAccountTypes = GservicesValue.value("finsky.supported_account_types", "com.google.work");
    surveySiteIdOverallApp = GservicesValue.value("finsky.hats.survey_site_id_overall_app", "gxadhtcppqz4aewwxotbhbc5lm");
    surveySiteIdSearchResults = GservicesValue.value("finsky.hats.survey_site_id_search_results", "tiyln7mdroeylhev4m736lnsmy");
    surveySiteIdSearchResultsControlGroup = GservicesValue.value("finsky.hats.survey_site_id_search_results_control_group", "tvdzhhl47xlshtqukvrtdmfcim");
    gearheadExternalHostingLockout = GservicesValue.value("finsky.gearhead.external_hosting_lockout", Boolean.valueOf(true));
    wearNodeKeepTimeMs = GservicesValue.value("finsky.wear.node_keep_time_ms", Long.valueOf(2592000000L));
    wearDailyHygieneEnable = GservicesValue.value("finsky.wear.daily_hygiene_enable", Boolean.valueOf(true));
    wearSelfUpdateEnabled = GservicesValue.value("finsky.wear.self_update_enabled", Boolean.valueOf(false));
    wearGmsUpdateEnabled = GservicesValue.value("finsky.wear.gms_update_enabled", Boolean.valueOf(true));
    wearAutoUpdateWhitelist = GservicesValue.value("finsky.wear.auto_update_whitelist", "com.google.android.wearable.app,com.vinodkrishnan.testapp");
    wearGmsVersionDependencyEnabled = GservicesValue.value("finsky.wear.gms_version_dependency_enabled", Boolean.valueOf(true));
    directToBackendIntent = GservicesValue.value("finsky.direct_to_backend_intent", Boolean.valueOf(true));
    enableOkHttp = GservicesValue.value("finsky.enable_ok_http", Boolean.valueOf(true));
    preregistrationExpireAfterAcknowledgeMs = GservicesValue.value("finsky.preregistration_expire_after_acknowledge_ms", Long.valueOf(604800000L));
    preregistrationForceList = GservicesValue.value("finsky.preregistration_force_list", "");
    disableSidewinderSelfupdate = GservicesValue.value("finsky.disable_sidewinder_selfupdate", Boolean.valueOf(true));
    reauthApiGetSettingsEndpoint = GservicesValue.value("finsky.reauth_api_get_settings_end_point", "https://www.googleapis.com/reauth/v1beta/users/me/settings");
    reauthApiVerifyCredentialsEndpoint = GservicesValue.value("finsky.reauth_api_verify_credentials_end_point_with_delegation", "https://www.googleapis.com/reauth/v1beta/users/%user_id%/reauthProofTokens");
    reauthApiAuthTokenType = GservicesValue.value("finsky.reauth_api_auth_token_type", "oauth2:https://www.googleapis.com/auth/accounts.reauth");
    reauthApiAccountManagerKey = GservicesValue.value("finsky.reauth_api_account_manager_key", "com.google.android.gms.auth.confirm.CredentialsState");
    rapidAutoUpdateListing = GservicesValue.value("finsky.rapid_auto_update_listing_v2", "");
    rapidAutoUpdateTosMinVersion = GservicesValue.value("finsky.rapid_auto_update_tos_min_version", Integer.valueOf(5));
    backStackExpirationDurationMs = GservicesValue.value("finsky.backstack_expiration_duration_ms", Long.valueOf(57600000L));
    feedbackPackageMinimumVersion = GservicesValue.value("finsky.feedback_Package_Minimum_Version", Integer.valueOf(4132000));
    feedbackPackage = GservicesValue.value("finsky.feedback_package", "com.google.android.gms");
    legacyFeedbackPackage = GservicesValue.value("finsky.legacy_feedback_package", "com.google.android.feedback");
    familyManagementPackage = GservicesValue.value("finsky.family_management_package", "com.google.android.gms");
    minGmsCoreVersionForFamily = GservicesValue.value("finsky.min_gmscore_version_for_family", Integer.valueOf(8400000));
    locationMaxAgeMs = GservicesValue.value("finsky.location_max_age_ms", Long.valueOf(3600000L));
    homeBrowseUrlsForUserContextHeader = GservicesValue.value("finsky.home_browse_urls_for_user_context_header", "home?c=0,homeV2?c=3");
    searchSuggestThrottleIntervalMs = GservicesValue.value("finsky.search_suggest_throttle_interval_ms", Integer.valueOf(150));
    clusterPrivacySettingNoticeWindowTimeMs = GservicesValue.value("finsky.notice_window_time", Long.valueOf(300000L));
    showPackageRestoreNotifications = GservicesValue.value("finsky.show_package_restore_notifications", Boolean.valueOf(false));
    maxPrivacySettingNoticeSeenCount = GservicesValue.value("finsky.notice_max_notice_seen_count", Integer.valueOf(5));
    minLocationUpdateRangeMeters = GservicesValue.value("finsky.min_location_update_range_meters", Integer.valueOf(15000));
    helpUrlForCrashingIssues = GservicesValue.value("finsky.help_url_for_crashing_issues", "https://support.google.com/googleplay/?p=fix_crashing&hl=%lang%");
    helpUrlForDownloadIssues = GservicesValue.value("finsky.help_url_for_download_issues", "https://support.google.com/googleplay/?p=fix_download_install&hl=%lang%");
    helpUrlForConnectionIssues = GservicesValue.value("finsky.help_url_for_connection_issues", "https://support.google.com/googleplay/?p=fix_connectivity&hl=%lang%");
    helpUrlForStorageIssues = GservicesValue.value("finsky.help_url_for_storage_issues", "https://support.google.com/googleplay/?p=fix_storage&hl=%lang%");
    helpUrlForPurchaseIssues = GservicesValue.value("finsky.help_url_for_purchase_issues", "https://support.google.com/googleplay/?p=fix_purchasing&hl=%lang%");
    helpUrlForGeneralIssues = GservicesValue.value("finsky.help_url_for_general_issues", "https://support.google.com/googleplay/?p=fix_general&hl=%lang%");
    helpUrlForExternalStorageMissing = GservicesValue.value("finsky.help_url_for_external_storage_missing", "https://support.google.com/android-one/answer/6088895?hl=%lang%");
    dfeManagedContextDetectionEnabled = GservicesValue.value("finsky.dfe_managed_context_detection_enabled", Boolean.valueOf(true));
    deviceManagementHelperEnabled = GservicesValue.value("finsky.device_management_helper_enabled", Boolean.valueOf(true));
    showMyAccountNewsstandsMessage = GservicesValue.value("finsky.client_show_my_account_newsstands_message", Boolean.valueOf(true));
    emailToReportBadAd = GservicesValue.value("finsky.email_to_report_bad_ad", "report-bad-play-ad@google.com");
    adIdMinGmsCoreVersion = GservicesValue.value("finsky.adid_min_gms_core_version", Integer.valueOf(7000000));
    adIdMaxCacheTimeMs = GservicesValue.value("finsky.adid_max_cache_time_ms", Long.valueOf(82800000L));
    giftMessageMaxCharacterCount = GservicesValue.value("finsky.gift_message_max_character_count", Integer.valueOf(200));
    flushLogsNoUserActivityTimeoutMs = GservicesValue.value("finsky.flush_logs_no_user_activity_timeout", Long.valueOf(10000L));
    flushLogsOnAppExitTimeoutMs = GservicesValue.value("finsky.flush_logs_on_app_exit_timeout", Long.valueOf(60000L));
    flushLogsOnAppExitSelfUpdateTimeoutMs = GservicesValue.value("finsky.flush_logs_on_app_exit_self_update_timeout", Long.valueOf(300000L));
    flushLogsWaitTimeoutMs = GservicesValue.value("finsky.flush_logs_wait_timeout", Long.valueOf(60000L));
    flushLogsScheduleExpiredTimeoutMs = GservicesValue.value("finsky.flush_logs_schedule_expired_timeout", Long.valueOf(3600000L));
    crashFileExpiredTimeoutMs = GservicesValue.value("finsky.crash_file_expired_timeout", Long.valueOf(216000000L));
    maxCrashCount = GservicesValue.value("finsky.max_crash_count", Integer.valueOf(20));
    minCrashCountToPurgeCache = GservicesValue.value("finsky.min_crash_count_purge_cache", Integer.valueOf(1));
    minCrashCountToPurgeIntermediateData = GservicesValue.value("finsky.min_crash_count_purge_intermediate_data", Integer.valueOf(3));
    minCrashCountToPurgeUserPreferences = GservicesValue.value("finsky.min_crash_count_purge_user_prefs", Integer.valueOf(-1));
    newsstandPostBaseUrl = GservicesValue.value("finsky.newsstand_article_view_url", "http://google.com/newsstand/s/");
    appInBgDurationForUpdatingExperimentsMs = GservicesValue.value("finsky.app_in_bg_duration_for_updating_experiments_ms", Integer.valueOf(1800000));
  }
}


/* Location:           F:\apktool\apktool\Google_Play_Store6.0.5\classes-dex2jar.jar
 * Qualified Name:     com.google.android.finsky.config.G
 * JD-Core Version:    0.7.0.1
 */